Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-18.04"

    config.vm.provision :shell, path: "medium-java-provision.sh"

    config.vm.synced_folder ".", "/home/vagrant/code"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
    end 
end
