Vagrant.configure("2") do |config|
    config.vm.box = "minimal/xenial64"

    config.vm.provision :shell, path: "minimal_provision.sh"

    config.vm.synced_folder ".", "/home/vagrant/code"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
    end 

    config.vm.network "forwarded_port", guest: 8000, host: 8080,
        host_ip: "127.0.0.1"
end
