Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

    config.vm.provision :shell, path: "medium-csc230-provision.sh"

    config.vm.synced_folder ".", "/home/vagrant/code"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
    end 

    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
end
