Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provision :shell, :inline => $PROVISION_SCRIPT

    config.vm.synced_folder ".", "/home/vagrant/stuff"

    config.vm.network :forwarded_port, guest:22, host: 10022, id: "ssh"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
end

$PROVISION_SCRIPT = <<EOF
    if [ -f "/var/vagrant_provision" ]; then
        exit 0
    fi

    # Notice that `sudo` is used here throughout

    set -x -e     # verbose output, stop on any error
    
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update -y

    sudo apt-get install -y gcc-5 > /dev/null 2>&1
    sudo apt-get install -y g++-5 > /dev/null 2>&1

    # gcc-7 and g++-7 are default installed, but that
    # might not necessarily be something upon which to
    # depend...

    sudo apt-get install -y gcc-9 > /dev/null 2>&1
    sudo apt-get install -y g++-9 > /dev/null 2>&1

    sudo apt-get install -y valgrind > /dev/null 2>&1
    sudo apt-get install -y gdb > /dev/null 2>&1

    sudo apt-get install -y python3.6 > /dev/null 2>&1
    sudo apt-get install -y python-pytest > /dev/null 2>&1
    sudo apt-get install -y tree > /dev/null 2>&1

    # Configure alternatives for python (python2.7, python3.6)
    # but where python3.6 is the default
    # sudo update-alternatives --remove-all python
    sudo update-alternatives --install /usr/bin/python \
        python /usr/bin/python2.7 10
    sudo update-alternatives --install /usr/bin/python \
        python /usr/bin/python3.6 20

    # Configure alternatives for g++ (g++-5, g++-7, g++-9)
    # but where g++-9 is the default
    # sudo update-alternatives --remove-all g++
    sudo update-alternatives --install /usr/bin/g++ \
        g++ /usr/bin/g++-5 10
    sudo update-alternatives --install /usr/bin/g++ \
        g++ /usr/bin/g++-7 20
    sudo update-alternatives --install /usr/bin/g++ \
        g++ /usr/bin/g++-9 30

    # Configure alternatives for gcc (gcc-5, gcc-7, gcc-9)
    # but where gcc-9 is the default
    # sudo update-alternatives --remove-all gcc
    sudo update-alternatives --install /usr/bin/gcc \
        gcc /usr/bin/gcc-5 10
    sudo update-alternatives --install /usr/bin/gcc \
        gcc /usr/bin/gcc-7 20
    sudo update-alternatives --install /usr/bin/gcc \
        gcc /usr/bin/gcc-9 30

    touch /var/vagrant_provision
EOF

