Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    config.vm.provision :shell, :inline => $PROVISION_SCRIPT

    config.vm.synced_folder ".", "/home/vagrant/stuff"

    config.vm.network :forwarded_port, guest:22, host: 10022, id: "ssh"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
end

$PROVISION_SCRIPT = <<EOF
    if [ -f "/var/vagrant_provision" ]; then
        exit 0
    fi

    # Notice that `sudo` is used here throughout

    set -x -e     # verbose output, stop on any error

    sudo apt-get update -y

    sudo apt-get install -y g++-5
    sudo apt-get install -y gcc-5
    sudo apt-get install -y python3.6

    sudo apt-get install -y python-pytest
    sudo apt-get install -y valgrind
    sudo apt-get install -y gdb
    sudo apt-get install -y tree

    touch /var/vagrant_provision
EOF

